# A common Dockerfile for creating an image for
# an application.
# It is assumed that the target executable is named
# "app" and sits in the root of the context.
FROM docker.io/tictactoverengineered/base

COPY ./ .