apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: bot
spec:
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: docker.io/tictactoverengineered/bot:{{ $.Chart.Version }}
          env:
            - name: API_BASE_URL
              value: "http://openapi:80/"
          ports:
            - containerPort: 2112
