apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: bot
spec:
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: docker.io/tictactoverengineered/bot:{{ $.Chart.Version }}
        env:
          - name: HONEYCOMB_API_KEY
            valueFrom:
              secretKeyRef:
                name: honeycomb-secret
                key: api_key
          - name: HONEYCOMB_DATASET
            value: {{ .Values.honeycomb.dataset }}
          - name: API_BASE_URL
            value: "http://api"