apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamerepo
  labels:
    app: gamerepo
spec:
  selector:
    matchLabels:
      app: gamerepo
  template:
    metadata:
      labels:
        app: gamerepo
    spec:
      containers:
      - name: gamerepo
        image: gamerepo-image
        ports:
        - containerPort: 8080
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: gamerepo
spec:
  selector:
    app: gamerepo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080