apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid
  labels:
    app: grid
spec:
  selector:
    matchLabels:
      app: grid
  template:
    metadata:
      labels:
        app: grid
    spec:
      containers:
      - name: grid
        image: docker.io/tictactoverengineered/grid-image:{{ .Values.image.version }}
        env:
          - name: HONEYCOMB_API_KEY
            valueFrom:
              secretKeyRef:
                name: honeycomb-secret
                key: api_key
          - name: HONEYCOMB_DATASET
            value: {{ .Values.honeycomb.dataset }}
        ports:
        - containerPort: 8080
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: grid
spec:
  selector:
    app: grid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080