apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid
  labels:
    app: grid
spec:
  selector:
    matchLabels:
      app: grid
  template:
    metadata:
      labels:
        app: grid
    spec:
      containers:
        - name: grid
          image: docker.io/tictactoverengineered/grid:{{ $.Chart.Version }}
          env:
            - name: placeholder
              value: TEST
            - name: SPACE-0-0
              value: space-0-0:80
            - name: SPACE-0-1
              value: space-0-1:80
            - name: SPACE-0-2
              value: space-0-2:80
            - name: SPACE-1-0
              value: space-1-0:80
            - name: SPACE-1-1
              value: space-1-1:80
            - name: SPACE-1-2
              value: space-1-2:80
            - name: SPACE-2-0
              value: space-2-0:80
            - name: SPACE-2-1
              value: space-2-1:80
            - name: SPACE-2-2
              value: space-2-2:80
          ports:
            - containerPort: 8080
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: grid
spec:
  selector:
    app: grid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
