apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid
  labels:
    app: tictactoe
    job: grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
      job: grid
  template:
    metadata:
      labels:
        app: tictactoe
        job: grid
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: http-metrics
    spec:
      containers:
        - name: grid
          image: docker.io/tictactoverengineered/grid:{{ $.Chart.Version }}
          env:
            - name: OTEL_JAEGER_ENDPOINT
              value:  {{ .Values.jaeger.http }}
            - name: placeholder
              value: TEST
            - name: SPACE-0-0
              value: space-0-0:80
            - name: SPACE-0-1
              value: space-0-1:80
            - name: SPACE-0-2
              value: space-0-2:80
            - name: SPACE-1-0
              value: space-1-0:80
            - name: SPACE-1-1
              value: space-1-1:80
            - name: SPACE-1-2
              value: space-1-2:80
            - name: SPACE-2-0
              value: space-2-0:80
            - name: SPACE-2-1
              value: space-2-1:80
            - name: SPACE-2-2
              value: space-2-2:80
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - name: http-metrics
              containerPort: 2112
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grid
spec:
  selector:
    app: tictactoe
    job: grid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
