apiVersion: apps/v1
kind: Deployment
metadata:
  name: turncontroller
  labels:
    app: tictactoe
    job: turncontroller
spec:
  selector:
    matchLabels:
      app: tictactoe
      job: turncontroller
  template:
    metadata:
      labels:
        app: tictactoe
        job: turncontroller
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: http-metrics
        phlare.grafana.com/scrape: "true"
        phlare.grafana.com/port: http-metrics
    spec:
      containers:
        - name: turncontroller
          image: docker.io/tictactoverengineered/turncontroller:{{ $.Chart.Version }}
          env:
            - name: OTEL_JAEGER_ENDPOINT
              value:  {{ .Values.jaeger.http }}
            - name: GRID_SERVER_TARGET
              value: "grid:80"
            - name: CURRENT_TURN_SERVER_TARGET
              value: "currentturn:80"
            - name: CHECKER_SERVER_TARGET
              value: "checker:80"
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - name: http-metrics
              containerPort: 2112
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: turncontroller
spec:
  selector:
    app: tictactoe
    job: turncontroller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
