apiVersion: apps/v1
kind: Deployment
metadata:
  name: currentturn
  labels:
    app: tictactoe
    job: currentturn
spec:
  selector:
    matchLabels:
      app: tictactoe
      job: currentturn
  template:
    metadata:
      labels:
        app: tictactoe
        job: currentturn
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: http-metrics
    spec:
      containers:
        - name: currentturn
          image: docker.io/tictactoverengineered/currentturn:{{ $.Chart.Version }}
          env:
            - name: OTEL_JAEGER_ENDPOINT
              value:  {{ .Values.jaeger.http }}
            - name: placeholder
              value: TEST
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - name: http-metrics
              containerPort: 2112
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: currentturn
spec:
  selector:
    app: tictactoe
    job: currentturn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
