FROM alpine
WORKDIR /root

build:
    ARG VERSION=dev
    BUILD --build-arg SERVICE=turncontroller ../+gobuild

docker:
    ARG VERSION=dev
    ARG REGISTRY
    ARG IMAGE_REF=$REGISTRY/turncontroller:$VERSION
    BUILD --build-arg SERVICE=turncontroller --build-arg VERSION=$VERSION --build-arg IMAGE_REF=$IMAGE_REF ../+docker