FROM ../../../+protobuild

protos:
    COPY repo.proto .
    RUN protoc --go_out=plugins=grpc:. \
    --go_opt=paths=source_relative \
    repo.proto 
    SAVE ARTIFACT repo.pb.go repo.pb.go AS LOCAL repo.pb.go