apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamerepo
  labels:
    app: tictactoe
    job: gamerepo
spec:
  selector:
    matchLabels:
      app: tictactoe
      job: gamerepo
  template:
    metadata:
      labels:
        app: tictactoe
        job: gamerepo
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: http-metrics
        phlare.grafana.com/scrape: "true"
        phlare.grafana.com/port: http-metrics
    spec:
      containers:
        - name: gamerepo
          image: docker.io/tictactoverengineered/gamerepo:{{ $.Chart.Version }}
          env:
            - name: OTEL_JAEGER_ENDPOINT
              value:  {{ .Values.jaeger.http }}
            - name: STORAGE_TYPE
              value: {{ .Values.storage.type }}
            {{- if eq .Values.storage.type "mongodb"}} 
            - name: MONGO_CONN
              value: {{ template "templates.storage.mongodb.connection" . }}
            {{- end}}
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - name: http-metrics
              containerPort: 2112
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gamerepo
spec:
  selector:
    app: tictactoe
    job: gamerepo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
