apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamerepo
  labels:
    app: gamerepo
spec:
  selector:
    matchLabels:
      app: gamerepo
  template:
    metadata:
      labels:
        app: gamerepo
    spec:
      containers:
      - name: gamerepo
        image: docker.io/tictactoverengineered/gamerepo:{{ $.Chart.Version }}
        env:
          - name: HONEYCOMB_API_KEY
            valueFrom:
              secretKeyRef:
                name: honeycomb-secret
                key: api_key
          - name: HONEYCOMB_DATASET
            value: {{ .Values.honeycomb.dataset }}
          - name: MONGO_CONN
            value: {{ template "templates.mongodb.connection" . }}
        ports:
        - containerPort: 8080
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: gamerepo
spec:
  selector:
    app: gamerepo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080