# Based on https://medium.com/@dilipkumar/standalone-mongodb-on-kubernetes-cluster-19e7b5896b27
{{ if and (eq .Values.storage.type "mongodb") (.Values.storage.mongodb.statefulset) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
  namespace: tictactoe
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
      job: database
  template:
    metadata:
      labels:
        app: tictactoe
        job: database
        selector: mongodb-standalone
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo:4.0.8
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: tictactoe
  labels:
    app: tictactoe
    job: database
spec:
  clusterIP: None
  selector:
    app: tictactoe
    job: database
{{ end }}