/**
 * Tic Tac Toe
 * An API for games of Tic Tac Toe
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tom.w.elliott@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TicTacToe);
  }
}(this, function(expect, TicTacToe) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TicTacToe.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('currentPlayer', function() {
      it('should call currentPlayer successfully', function(done) {
        //uncomment below and update the code to test currentPlayer
        //instance.currentPlayer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gameGrid', function() {
      it('should call gameGrid successfully', function(done) {
        //uncomment below and update the code to test gameGrid
        //instance.gameGrid(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('index', function() {
      it('should call index successfully', function(done) {
        //uncomment below and update the code to test index
        //instance.index(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('matchStatus', function() {
      it('should call matchStatus successfully', function(done) {
        //uncomment below and update the code to test matchStatus
        //instance.matchStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('play', function() {
      it('should call play successfully', function(done) {
        //uncomment below and update the code to test play
        //instance.play(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('requestMatch', function() {
      it('should call requestMatch successfully', function(done) {
        //uncomment below and update the code to test requestMatch
        //instance.requestMatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('requestMatchPair', function() {
      it('should call requestMatchPair successfully', function(done) {
        //uncomment below and update the code to test requestMatchPair
        //instance.requestMatchPair(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('winner', function() {
      it('should call winner successfully', function(done) {
        //uncomment below and update the code to test winner
        //instance.winner(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
