FROM alpine
WORKDIR /root

build:
    ARG VERSION=dev
    BUILD --build-arg SERVICE=space ../+gobuild

docker:
    ARG VERSION=dev
    ARG REGISTRY
    ARG IMAGE_REF=$REGISTRY/space:$VERSION
    BUILD --build-arg SERVICE=space --build-arg VERSION=$VERSION --build-arg IMAGE_REF=$IMAGE_REF ../+docker