---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: {{ .Values.routes.api }}
        pathType: Prefix
        backend:
          serviceName: api
          servicePort: 80