---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: {{ .Values.ingress.api.host }}
    http:
      paths:
      - path: {{ .Values.ingress.api.path }}
        pathType: Prefix
        backend:
          service:
            name: api
            port: 
              number: 80