---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: {{ .Values.ingress.api.host }}
    http:
      paths:
      - path: {{ .Values.ingress.api.path }}
        pathType: Prefix
        backend:
          serviceName: api
          servicePort: 80