apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
      component: all-in-one
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
        component: all-in-one
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "16686"
    spec:
        containers:
          - image: jaegertracing/all-in-one
            name: jaeger
            ports:
              - containerPort: 16686
                protocol: TCP
              - containerPort: 14250
                protocol: TCP
            readinessProbe:
              httpGet:
                path: "/"
                port: 14269
              initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    app: jaeger
    component: jaeger-query
spec:
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger
    component: all-in-one
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
    component: jaeger-collector
spec:
  ports:
  - name: jaeger-collector-model
    port: 14250
    protocol: TCP
    targetPort: 14250
  selector:
    app: jaeger
    component: all-in-one
  type: ClusterIP