
FROM ../../../../+protobuild

protos:
    COPY grid.proto .
    RUN protoc --go_out=plugins=grpc:. \
    --go_opt=paths=source_relative \
    grid.proto 
    SAVE ARTIFACT grid.pb.go grid.pb.go AS LOCAL grid.pb.go
    SAVE ARTIFACT grid.proto grid.proto