FROM ../../../+protobuild

protos:
    COPY matchmaker.proto .
    RUN protoc --go_out=plugins=grpc:. \
    --go_opt=paths=source_relative \
    --experimental_allow_proto3_optional \
    matchmaker.proto
    SAVE ARTIFACT matchmaker.pb.go matchmaker.pb.go AS LOCAL matchmaker.pb.go