pipeline:
  identifier: Build_theothertomelliott_tic_tac_toverengineered_1709457958718
  name: Build tic-tac-toverengineered
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1709457905524
        repoName: theothertomelliott/tic-tac-toverengineered
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: make
                  spec:
                    shell: Sh
                    command: make
                  timeout: ""
                  type: Run
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
