apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: docker.io/tictactoverengineered/web:{{ $.Chart.Version }}
          env:
            - name: API_BASE_URL
              value: "http://api{{ .Values.routes.api }}"
            - name: OPENAPI_BASE_URL
              value: "http://openapi"
            - name: ROUTE_PREFIX
              value: {{ .Values.routes.web }}
          ports:
            - containerPort: 8080
