---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web
spec:
  rules:
  - host: {{ .Values.ingress.web.host }}
    http:
      paths:
      - path: {{ .Values.ingress.web.path }}
        pathType: Prefix
        backend:
          serviceName: web
          servicePort: 80