FROM alpine
WORKDIR /root

build:
    ARG VERSION=dev
    BUILD --build-arg VERSION=$VERSION --build-arg SERVICE=bot ../+gobuild

docker:
    ARG VERSION=dev
    ARG REGISTRY
    ARG IMAGE_REF=$REGISTRY/bot:$VERSION
    BUILD --build-arg SERVICE=bot --build-arg VERSION=$VERSION --build-arg IMAGE_REF=$IMAGE_REF ../+docker