apiVersion: apps/v1
kind: Deployment
metadata:
  name: space
  labels:
    app: space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space
  template:
    metadata:
      labels:
        app: space
    spec:
      containers:
    {{- $root := . -}}
    {{- range $i := tuple 0 1 2 -}}
      {{- range $j := tuple 0 1 2 }}
      - name: space-{{ $i }}-{{ $j }}
        image: docker.io/tictactoverengineered/space:{{ $root.Chart.Version }}
        env:
          - name: OTEL_JAEGER_ENDPOINT
            value:  {{ $root.Values.jaeger.http }}
          - name: PORT
            value: "80{{ $i }}{{ $j }}"
          - name: XPOS
            value: "{{ $i }}"
          - name: YPOS
            value: "{{ $j }}"
          - name: STORAGE_TYPE
            value: {{ $root.Values.storage.type }}
          {{- if eq $root.Values.storage.type "mongodb"}}
          - name: MONGO_CONN
            value: {{ template "templates.storage.mongodb.connection" $root }}
          {{- end }}
        ports:
        - containerPort: 80{{ $i }}{{ $j }}
      {{- end }}
    {{- end }}