{{- $root := . -}}
{{- range $i := tuple 0 1 2 -}}
  {{- range $j := tuple 0 1 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-{{ $i }}-{{ $j }}
  labels:
    app: space
    space: {{ $i }}-{{ $j }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space
      space: {{ $i }}-{{ $j }}
  template:
    metadata:
      labels:
        app: space
        space: {{ $i }}-{{ $j }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: http-metrics
    spec:
      containers:
      - name: space
        image: docker.io/tictactoverengineered/space:{{ $root.Chart.Version }}
        env:
          - name: OTEL_JAEGER_ENDPOINT
            value:  {{ $root.Values.jaeger.http }}
          - name: PORT
            value: "8080"
          - name: XPOS
            value: "{{ $i }}"
          - name: YPOS
            value: "{{ $j }}"
          - name: STORAGE_TYPE
            value: {{ $root.Values.storage.type }}
          {{- if eq $root.Values.storage.type "mongodb"}}
          - name: MONGO_CONN
            value: {{ template "templates.storage.mongodb.connection" $root }}
          {{- end }}
        ports:
        - containerPort: 8080
        - name: http-metrics
          containerPort: 2112
          protocol: TCP
  {{- end }}
{{- end }}