{{- range $i := tuple 0 1 2 -}}
  {{- range $j := tuple 0 1 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: space-{{ $i }}-{{ $j }}
spec:
  selector:
    app: space
    space: {{ $i }}-{{ $j }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  {{- end }}
{{- end }}