apiVersion: apps/v1
kind: Deployment
metadata:
  name: checker
  labels:
    app: tictactoe
    job: checker
spec:
  selector:
    matchLabels:
      app: tictactoe
      job: checker
  template:
    metadata:
      labels:
        app: tictactoe
        job: checker
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: http-metrics
        phlare.grafana.com/scrape: "true"
        phlare.grafana.com/port: http-metrics
    spec:
      containers:
        - name: checker
          image: docker.io/tictactoverengineered/checker:{{ $.Chart.Version }}
          env:
            - name: OTEL_JAEGER_ENDPOINT
              value:  {{ .Values.jaeger.http }}
            - name: GRID_SERVER_TARGET
              value: "grid:80"
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - name: http-metrics
              containerPort: 2112
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: checker
spec:
  selector:
    app: tictactoe
    job: checker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
