/**
 * Tic Tac Toe
 * An API for games of Tic Tac Toe
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tom.w.elliott@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GridAllOf from './GridAllOf';

/**
 * The Grid model module.
 * @module model/Grid
 * @version 1.0.0
 */
class Grid {
    /**
     * Constructs a new <code>Grid</code>.
     * @alias module:model/Grid
     * @implements module:model/GridAllOf
     * @param grid {Array.<Array.<String>>} 
     */
    constructor(grid) { 
        GridAllOf.initialize(this, grid);
        Grid.initialize(this, grid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, grid) { 
        obj['grid'] = grid;
    }

    /**
     * Constructs a <code>Grid</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Grid} obj Optional instance to populate.
     * @return {module:model/Grid} The populated <code>Grid</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Grid();
            GridAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('grid')) {
                obj['grid'] = ApiClient.convertToType(data['grid'], [['String']]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Array.<String>>} grid
 */
Grid.prototype['grid'] = undefined;


// Implement GridAllOf interface:
/**
 * @member {Array.<Array.<String>>} grid
 */
GridAllOf.prototype['grid'] = undefined;




export default Grid;

