/**
 * Tic Tac Toe
 * An API for games of Tic Tac Toe
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tom.w.elliott@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MatchPendingAllOf model module.
 * @module model/MatchPendingAllOf
 * @version 1.0.0
 */
class MatchPendingAllOf {
    /**
     * Constructs a new <code>MatchPendingAllOf</code>.
     * @alias module:model/MatchPendingAllOf
     * @param requestID {String} 
     */
    constructor(requestID) { 
        
        MatchPendingAllOf.initialize(this, requestID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requestID) { 
        obj['requestID'] = requestID;
    }

    /**
     * Constructs a <code>MatchPendingAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchPendingAllOf} obj Optional instance to populate.
     * @return {module:model/MatchPendingAllOf} The populated <code>MatchPendingAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchPendingAllOf();

            if (data.hasOwnProperty('requestID')) {
                obj['requestID'] = ApiClient.convertToType(data['requestID'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} requestID
 */
MatchPendingAllOf.prototype['requestID'] = undefined;






export default MatchPendingAllOf;

