/**
 * Tic Tac Toe
 * An API for games of Tic Tac Toe
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tom.w.elliott@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Position model module.
 * @module model/Position
 * @version 1.0.0
 */
class Position {
    /**
     * Constructs a new <code>Position</code>.
     * @alias module:model/Position
     * @param i {Number} 
     * @param j {Number} 
     */
    constructor(i, j) { 
        
        Position.initialize(this, i, j);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, i, j) { 
        obj['i'] = i;
        obj['j'] = j;
    }

    /**
     * Constructs a <code>Position</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Position} obj Optional instance to populate.
     * @return {module:model/Position} The populated <code>Position</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Position();

            if (data.hasOwnProperty('i')) {
                obj['i'] = ApiClient.convertToType(data['i'], 'Number');
            }
            if (data.hasOwnProperty('j')) {
                obj['j'] = ApiClient.convertToType(data['j'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} i
 */
Position.prototype['i'] = undefined;

/**
 * @member {Number} j
 */
Position.prototype['j'] = undefined;






export default Position;

