/**
 * Tic Tac Toe
 * An API for games of Tic Tac Toe
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tom.w.elliott@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WinnerAllOf from './WinnerAllOf';

/**
 * The Winner model module.
 * @module model/Winner
 * @version 1.0.0
 */
class Winner {
    /**
     * Constructs a new <code>Winner</code>.
     * @alias module:model/Winner
     * @implements module:model/WinnerAllOf
     */
    constructor() { 
        WinnerAllOf.initialize(this);
        Winner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Winner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Winner} obj Optional instance to populate.
     * @return {module:model/Winner} The populated <code>Winner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Winner();
            WinnerAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('winner')) {
                obj['winner'] = ApiClient.convertToType(data['winner'], 'String');
            }
            if (data.hasOwnProperty('draw')) {
                obj['draw'] = ApiClient.convertToType(data['draw'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} winner
 */
Winner.prototype['winner'] = undefined;

/**
 * @member {Boolean} draw
 */
Winner.prototype['draw'] = undefined;


// Implement WinnerAllOf interface:
/**
 * @member {String} winner
 */
WinnerAllOf.prototype['winner'] = undefined;
/**
 * @member {Boolean} draw
 */
WinnerAllOf.prototype['draw'] = undefined;




export default Winner;

