FROM alpine
WORKDIR /root

build:
    ARG VERSION=dev
    BUILD --build-arg VERSION=$VERSION --build-arg SERVICE=checker ../+gobuild

docker:
    ARG VERSION=dev
    ARG REGISTRY
    ARG IMAGE_REF=$REGISTRY/checker:$VERSION
    BUILD --build-arg SERVICE=checker --build-arg VERSION=$VERSION --build-arg IMAGE_REF=$IMAGE_REF ../+docker