apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: docker.io/tictactoverengineered/api:{{ $.Chart.Version }}
        env:
          {{- include "templates.honeycomb.env" . | nindent 10 }}
          - name: REPO_SERVER_TARGET
            value: "gamerepo:80"
          - name: GRID_SERVER_TARGET
            value: "grid:80"
          - name: CURRENT_TURN_SERVER_TARGET
            value: "currentturn:80"
          - name: CHECKER_SERVER_TARGET
            value: "checker:80"
          - name: TURN_CONTROLLER_SERVER_TARGET
            value: "turncontroller:80"
          - name: ROUTE_PREFIX
            value: {{ .Values.routes.api }}
        ports:
        - containerPort: 8080