name: 'dependencies'
description: 'sets up common dependencies for all jobs'
inputs:
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: composite
  steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.17.0'
        repo-token: ${{ inputs.token }}
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4' # The Go version to download (if necessary) and use.
    - name: Set up Go cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
