name: CI

on:
  push:
      tags:
        - v* # Run only on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Set output
      id: tagName
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check tag output
      env:
        RELEASE_VERSION: ${{ steps.tagName.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.tagName.outputs.tag }}
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Download latest earth
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.3.13/earth-linux-amd64 -O /usr/local/bin/earth && chmod +x /usr/local/bin/earth'"
    - name: Run tests
      run: earth +test
    - name: Build binaries and supporting files
      run: earth --build-arg VERSION=${{ steps.tagName.outputs.tag }} +buildall
    - name: Build and push Docker images
      run: earth -push --build-arg VERSION=${{ steps.tagName.outputs.tag }} +images
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0
    - name: Release Helm Chart
      uses: ./.github/actions/chart-release
      with:
        version: ${{ steps.tagName.outputs.tag }}
      env:
        GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"