name: TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependencies
      uses: ./.github/actions/dependencies
    - name: Run tests
      run: make testcover
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: b6b5d038c012195ee2235d9de3eb7258f4e0ff8e45523a39160bdb306566d61f
      with:
        coverageLocations: |
          ${{github.workspace}}/*.out:gocov
        prefix: github.com/theothertomelliott/tic-tac-toverengineered
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        uses: ./.github/actions/dependencies
      - name: Build binaries and supporting files
        run: make services
      - name: Build Docker images
        run: make docker
