name: TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dependencies
      uses: ./.github/actions/dependencies
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: make testcover
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: b6b5d038c012195ee2235d9de3eb7258f4e0ff8e45523a39160bdb306566d61f
      with:
        coverageLocations: |
          ${{github.workspace}}/*.out:gocov
        prefix: github.com/theothertomelliott/tic-tac-toverengineered
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dependencies
        uses: ./.github/actions/dependencies
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build binaries and supporting files
        run: make services
      - name: Build Docker images
        run: make docker
  tilt:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dependencies
        uses: ./.github/actions/dependencies
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Install tilt
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tilt
        run: tilt ci -- --disable_telemetry
