name: TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.17.0'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4' # The Go version to download (if necessary) and use.
    - name: Run tests and publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: b6b5d038c012195ee2235d9de3eb7258f4e0ff8e45523a39160bdb306566d61f
      with:
        coverageCommand: make testcover
        coverageLocations: ${{github.workspace}}/*.cov:gocov
    - name: Build binaries and supporting files
      run: make services
    - name: Build Docker images
      run: make docker