FROM alpine
WORKDIR /root

css:
    FROM node:14.14.0
    COPY --dir css .
    # TODO: Add NODE_ENV=production to below and configure correctly to build for prod
    RUN npx tailwindcss-cli@0.1.2 build ./css/styles.css -o ./public/css/tailwind.css
    SAVE ARTIFACT ./public/css AS LOCAL ./.output/public/css

build:
    ARG VERSION=dev
    BUILD --build-arg VERSION=$VERSION --build-arg SERVICE=web ../+gobuild
    BUILD +css
    COPY --dir views .
    SAVE ARTIFACT ./views AS LOCAL ./.output/views

docker:
    ARG VERSION=dev
    ARG REGISTRY
    ARG IMAGE_REF=$REGISTRY/web:$VERSION
    BUILD --build-arg SERVICE=web --build-arg VERSION=$VERSION --build-arg IMAGE_REF=$IMAGE_REF ../+docker